import { NextResponse } from "next/server";
import axios from "axios";
import {
  createContentType,
  getContentType,
  describeCsError,
} from "@/lib/contentstack";
import type {
  ContentstackContentType,
  ContentstackField,
  CreatePageTypeRequest,
  CreatePageTypeResponse,
} from "@/types";

export const runtime = "nodejs";

// Contentstack modular-blocks block definition (not in shared types because
// the `blocks` key is a non-standard extension on ContentstackField).
interface ModularBlock {
  title: string;
  uid: string;
  schema: ContentstackField[];
}

function buildPageContentType(
  pageTitle: string,
  pageUid: string,
  componentUids: string[],
  componentTitles: string[],
): ContentstackContentType & {
  schema: (
    | ContentstackField
    | (ContentstackField & { blocks: ModularBlock[] })
  )[];
} {
  const coreFields: ContentstackField[] = [
    // Title is mandatory and marks itself as the default display field.
    {
      display_name: "Title",
      uid: "title",
      data_type: "text",
      mandatory: true,
      unique: false,
      _default: true,
      field_metadata: { _default: true },
    },
    // URL / slug — simple text, no unique constraint to avoid creation errors.
    {
      display_name: "URL",
      uid: "url",
      data_type: "text",
      mandatory: false,
      unique: false,
      field_metadata: {},
    },
    {
      display_name: "SEO Title",
      uid: "seo_title",
      data_type: "text",
      mandatory: false,
      field_metadata: {},
    },
    {
      display_name: "SEO Description",
      uid: "seo_description",
      data_type: "text",
      mandatory: false,
      field_metadata: { multiline: true },
    },
  ];

  // One block type per selected component. Each block has a single reference
  // field that points back to the component's content type.
  const blocks: ModularBlock[] = componentUids.map((ctUid, i) => {
    const title = componentTitles[i] ?? ctUid;
    const blockUid = `${ctUid}_block`;
    return {
      title,
      uid: blockUid,
      schema: [
        {
          display_name: title,
          uid: `${ctUid}_ref`,
          data_type: "reference",
          field_metadata: {
            ref_multiple: false,
            ref_multiple_content_types: false,
          },
          // `reference_to` is not in the shared ContentstackField type but the
          // Contentstack API requires it — we spread it in below.
        } as ContentstackField,
      ],
    };
  });

  // Patch reference_to into each reference field after TypeScript is satisfied.
  blocks.forEach((block, bi) => {
    block.schema.forEach((f, fi) => {
      if (f.data_type === "reference") {
        (
          blocks[bi].schema[fi] as unknown as Record<string, unknown>
        ).reference_to = [componentUids[bi]];
      }
    });
  });

  const modularBlocksField = {
    display_name: "Modular Blocks",
    uid: "modular_blocks",
    data_type: "blocks",
    mandatory: false,
    multiple: true,
    field_metadata: {},
    ...(blocks.length > 0 ? { blocks } : {}),
  } as ContentstackField & { blocks?: ModularBlock[] };

  return {
    title: pageTitle,
    uid: pageUid,
    description:
      "Page content type with Modular Blocks — auto-generated by MigrateX",
    schema: [...coreFields, modularBlocksField],
    options: {
      is_page: true,
      singleton: false,
      title: "title",
      sub_title: [],
      // Use /{title} — references the guaranteed-present "title" field.
      // Users can edit the pattern in Contentstack afterwards.
      url_pattern: "/{title}",
      url_prefix: "/",
    },
  };
}

export async function POST(request: Request) {
  const body = (await request.json()) as CreatePageTypeRequest;

  if (!body?.config?.apiKey || !body?.pageUid || !body?.pageTitle) {
    return NextResponse.json<CreatePageTypeResponse>(
      { ok: false, error: "bad_request" },
      { status: 400 },
    );
  }

  const schema = buildPageContentType(
    body.pageTitle,
    body.pageUid,
    body.componentUids ?? [],
    body.componentTitles ?? [],
  );

  console.log("[create-page-type] schema:", JSON.stringify(schema, null, 2));

  try {
    const existing = await getContentType(body.config, schema.uid);
    if (existing) {
      console.log(
        `[create-page-type] "${schema.uid}" already exists — reusing`,
      );
      return NextResponse.json<CreatePageTypeResponse>({
        ok: true,
        contentType: existing,
      });
    }

    const created = await createContentType(body.config, schema);
    return NextResponse.json<CreatePageTypeResponse>({
      ok: true,
      contentType: created,
    });
  } catch (err) {
    // Expose the full Contentstack error body so the client sees it too.
    let message = describeCsError(err);
    if (axios.isAxiosError(err) && err.response?.data) {
      const data = err.response.data as Record<string, unknown>;
      const detail = JSON.stringify(data);
      console.error("[create-page-type] CS error body:", detail);
      message = `${message} | ${detail}`;
    }
    return NextResponse.json<CreatePageTypeResponse>(
      { ok: false, error: message },
      { status: 502 },
    );
  }
}
